### ISSUE TITLE
You're sending plaintext passwords

### ISSUE THREAD

**Issue by rol4400** [gearbox-solutions/nuxt-auth-example#1]
In this example the passwords are hashed in the server api routes not in the front end so passwords are being sent in plain text to the server

**Comment by Smef** [comment]
You should use https with a valid SSL certificate to make sure that the passwords are encrypted in transit. This is handled by the web server or reverse proxy, and not in the JS code in the browser. The hashing can only be done on the server, as that where the salt and hashing method are stored and coded. You can't do this client-side without exposing secure information.

All that being said, this is an example of implementing the library. If you have questions about the library itself you should [comment on there directly](https://github.com/atinux/nuxt-auth-utils).
