### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by bnbc** [gearbox-solutions/nuxt-auth-example#2]
Hello !
I have an error with `pnpm drizzle-run-migrations`

```
> nuxt-app@ drizzle-run-migrations /var/www/apps/yookkan/nuxt-auth-example
> jiti ./database/migrations/run.ts

Migrations failed
Error: connect ECONNREFUSED 127.0.0.1:3306
```

My .env is : 

```
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=nuxt_auth_example
DB_USERNAME=root
DB_PASSWORD=rootpassword

NUXT_SESSION_PASSWORD=d531a58faa90425dabe4dcced7b49114
```

Something i missed ?
I have to install db ? 
I'm on WSL.
Thks !

**Comment by Smef** [comment]
This is trying to connect to a database server on your local machine based on the values you have entered there. Yes, you need to have a database server running for it to connect to. [DBngin](https://dbngin.com/) is a great way to get one running locally very quickly if you don't have another configuration.

**Comment by bnbc** [comment]
Ok nice thks !
